package com.privatemessenger.platform

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.channels.awaitClose

/**
 * iOS actual for [XmtpService].
 *
 * The xmtp-ios SDK is a native Swift library. It cannot be imported directly from
 * Kotlin/Native. Instead, the Swift host app provides a thin ObjC-compatible wrapper
 * (XmtpClientWrapper) that is compiled into the iOS framework. This class calls into
 * that wrapper via the Kotlin/Native ObjC interop layer.
 *
 * The wrapper is declared in iosApp/iosApp/XmtpClientWrapper.swift and exports:
 *   @objc class XmtpClientWrapper : NSObject { ... }
 * which appears to Kotlin as XmtpClientWrapper from the iosApp framework.
 *
 * NOTE: This is a stub that will be wired to the real ObjC interop
 * once the Xcode project is compiled together with the shared framework.
 * The interface contract is final; only the call-sites change.
 */
actual class XmtpService {

    actual suspend fun createClient(
        privateKeyHex: String,
        dbEncryptionKey: ByteArray,
    ): XmtpClientHandle {
        // XmtpClientWrapper is the ObjC-exported Swift class
        // It is generated by the Xcode project and available at compile time on iOS.
        val wrapper = XmtpClientWrapper.createWithPrivateKeyHex(
            privateKeyHex = privateKeyHex,
            dbEncryptionKey = dbEncryptionKey.toNSData(),
        )
        return XmtpClientHandle(wrapper)
    }

    actual fun getInboxId(client: XmtpClientHandle): String =
        (client.raw as XmtpClientWrapper).inboxId

    actual fun getPublicAddress(client: XmtpClientHandle): String =
        (client.raw as XmtpClientWrapper).publicAddress

    actual suspend fun canMessage(client: XmtpClientHandle, ethereumAddress: String): Boolean =
        (client.raw as XmtpClientWrapper).canMessage(ethereumAddress)

    actual suspend fun findOrCreateDm(client: XmtpClientHandle, ethereumAddress: String): String =
        (client.raw as XmtpClientWrapper).findOrCreateDm(ethereumAddress)

    actual suspend fun newGroup(client: XmtpClientHandle, memberInboxIds: List<String>): String =
        (client.raw as XmtpClientWrapper).newGroup(memberInboxIds)

    actual suspend fun sendMessage(
        client: XmtpClientHandle,
        conversationId: String,
        text: String,
    ): String = (client.raw as XmtpClientWrapper).sendMessage(conversationId, text)

    actual suspend fun syncConversations(client: XmtpClientHandle) {
        (client.raw as XmtpClientWrapper).syncConversations()
    }

    actual fun streamAllMessages(client: XmtpClientHandle): Flow<IncomingMessage> = callbackFlow {
        val wrapper = client.raw as XmtpClientWrapper
        // The Swift wrapper accepts a callback block and calls it for each message.
        val streamHandle = wrapper.streamAllMessages { id, convId, senderId, body, sentAtMs ->
            if (!body.matches(Regex("^(@[a-fA-F0-9]{40,}\\s*)+"))) {
                trySend(IncomingMessage(id, convId, senderId, body, sentAtMs))
            }
        }
        awaitClose { streamHandle.cancel() }
    }

    // ── Helper ───────────────────────────────────────────────────────────────

    private fun ByteArray.toNSData(): platform.Foundation.NSData {
        return kotlinx.cinterop.memScoped {
            val ptr = kotlinx.cinterop.allocArray<kotlinx.cinterop.ByteVar>(size)
            for (i in indices) ptr[i] = this@toNSData[i]
            platform.Foundation.NSData.create(bytes = ptr, length = size.toULong())
        }
    }
}
